name: ✅ AIモデル回答品質チェック
description: ベースモデルとファインチューニング済みモデルの回答品質を比較・確認します。
title: "✅ 品質チェック: "
labels: ["model-comparison"]
body:
  - type: textarea
    id: prompt
    attributes:
      label: Prompt
      description: The prompt to send to both models.
      placeholder: Enter your prompt here...
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 参照回答
      description: 意味的類似度の算出に使用します。入力しない場合はスキップされます。
      placeholder: 理想的な回答例を入力してください（任意）
    validations:
      required: false

